apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: mysqldb

spec:
  serviceName: mysqldb
  replicas: 1

  selector:
    matchLabels:
      app: mysqldb

  template:
    metadata:
      labels:
        app: mysqldb

    spec:
      imagePullSecrets:
        - name: mysecret

      initContainers:
        - name: prepare-mysql-data-directory
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              mkdir -p /mnt/mysql
              chmod 777 /mnt/mysql
          volumeMounts:
            - name: mysql-data
              mountPath: /mnt

      containers:
        - name: mysqldb
          image: jyothsnav/clientapp:dbimage
          imagePullPolicy: Always

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password

          ports:
            - name: mysql
              containerPort: 3306

          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
              subPath: mysql

  volumeClaimTemplates:
    - metadata:
        name: mysql-data

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi
