apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: mysqldb

spec:
  serviceName: mysqldb
  replicas: 1

  selector:
    matchLabels:
      app: mysqldb

  template:
    metadata:
      labels:
        app: mysqldb

    spec:
      imagePullSecrets:
        - name: mysecret

      containers:
        - name: mysqldb
          image: jyothsnav/clientapp:dbimage

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password

          ports:
            - name: mysql
              containerPort: 3306

          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: mysql-data

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi
